### ISSUE TITLE
Entries get overwritten in Index buffer

### ISSUE THREAD

**Issue by pranavtbhat** [JuliaComputing/NDSparseData.jl#15]
Overwriting new entries in the index buffer before a `flush!` takes place can produce buggy behavior. 

```julia
a = NDSparse((10, 10), [1,2,3,4], [1,2,3,4], [1,2,3,4])
# NDSparse{Int64,2,Tuple{Int64,Int64}}:
# (1,1) => 1
# (2,2) => 2
# (3,3) => 3
# (4,4) => 4

a[5,5] = 5
# 5

a[5,5] = 6
# 6

 a
#NDSparse{Int64,2,Tuple{Int64,Int64}}:
# (1,1) => 1
# (2,2) => 2
# (3,3) => 3
# (4,4) => 4
# (5,5) => 5
# (5,5) => 6

a[5,5]
# 0
```

One way to handle this would be to replace the index buffer with a dictionary.

**Comment by JeffBezanson** [comment]
I think `getindex` should be changed to throw an error for missing or multi-valued keys (like KeyError in Dicts, or BoundsError for arrays). We might even want to remove the default value altogether.

Then we need to decide whether duplicate index entries are allowed. So far I have been allowing it, and doing aggregation in a separate step. Instead, we could have an optional aggregation function argument for all functions that might produce duplicate entries. If we use stable sorts and `(x,y)->y` as the default aggregator, overwriting behavior should work right. This design would probably be better, since it avoids storing duplicate entries.
